# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '*.sln'
  buildproject: '**/APKInstaller/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: 'Clone ModernWpf'
  inputs:
    script: |
      echo 'Cloning into sources folder at: $(Build.SourcesDirectory)\..\ModernWpf'
      git clone https://github.com/wherewhere/ModernWpf.git --progress --branch master --single-branch --depth=1 $(Build.SourcesDirectory)\..\ModernWpf
      exit

- task: CmdLine@2
  displayName: 'Clone SharpAdbClient'
  inputs:
    script: |
      echo 'Cloning into sources folder at: $(Build.SourcesDirectory)\..\AdvancedSharpAdbClient'
      git clone https://github.com/wherewhere/AdvancedSharpAdbClient.git --progress --branch main --single-branch --depth=1 $(Build.SourcesDirectory)\..\AdvancedSharpAdbClient
      exit

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: 
    configuration: '$(buildConfiguration)'
    arguments: '-r win7-x64
                -o $(build.artifactStagingDirectory)
                -p:PublishSingleFile=true
                -p:PublishReadyToRun=true'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'